### ISSUE TITLE
Suggest that you add tiny contents into your README

### ISSUE THREAD

**Issue by Alghost** [gluster/libgfapi-perl#1]
Hi, I'm a new in perl.

so, I had been confused when using this binding because of error message.

It means that this binding does not work if glusterfs-api-devel is not installed on systems.

so I think you are supposed to add requirements into your README like below;

* To use this, you have to install glusterfs devel packages such as glusterfs-devel and glusterfs-api-devel

Thanks.

**Comment by potatogim** [comment]
Ye, it is good suggestion!

Could you open new PR that reflects this suggestion? :smile:
